site_name: Efitrac
site_url: http://efitrac.com
site_description: Documentation for Efitrac Project
site_author: Efitrac

repo_url: https://github.com/pararaton/efitrac-wiki

pages:
- Home: index.md
- End User Guide:
    - Menu: enduser/menu.md
    - Access Control List (ACL): enduser/acl/access-control-list.md
    - Access Control List - Adv: enduser/acl/access-control-list-adv.md
    - Dashboard View: enduser/dashboard-view.md
- Developer:
    - API:
        - Overview: api/overview.md
        - Controller: api/controller.md
        - Storage: api/storage/storage.md
        - Logout: api/logout.md   # Logout selalu diletakkan di paling bawah.	
    - Model:
        - AbstractModel: developer/abstractmodel.md
    - Basic Views:
        - Overview: developer/basic/overview.md
        - Tree view: developer/basic/tree.md
        - Form view: developer/basic/form.md
        - Search view: developer/basic/search.md
    - Advanced Views:
        - Overview: developer/advanced/overview.md
        - Tree view: developer/advanced/tree.md
        - Search view: developer/advanced/form.md
        - Kanban view: developer/advanced/kanban.md
        - Graph view: developer/advanced/graph.md
        - Gantt view: developer/advanced/gantt.md
        - Calendar view: developer/advanced/calendar.md
    - Custom View: developer/custom-view.md
    - Multiple View: developer/multiple-view.md
    - Inheritance:
        - Model Inheritance: developer/inheritance/model-inheritance.md
        - View Inheritance: developer/inheritance/view-inheritance.md
    - Default Search Filter: developer/default-search-filter.md
    - ActionButton:
        - PopUp Window : developer/action-button/popup-window.md
    - Domain: developer/domain.md
    - Versioning: developer/versioning.md
- Module Release Notes:
    - Sales: modules/sales.md
- About:
    - System Changes: about/release-notes.md
    - Contact Us: about/contact.md

markdown_extensions:
    - toc:
        permalink: true