site_name: Efitrac
site_url: http://efitrac.com
site_description: Documentation for Efitrac Project
site_author: Efitrac

repo_url: https://github.com/pararaton/efitrac-wiki

pages:
- Home: index.md
- End User Guide:
    - Menu: enduser/menu.md
    - Access Control List (ACL): enduser/acl/access-control-list.md
    - Access Control List - Adv: enduser/acl/access-control-list-adv.md
- Developer:
    - Custom View: developer/custom-view.md
    - Domain: developer/domain.md
    - Inherit View: developer/inherit-view.md
    - Versionning: developer/versioning.md
- Module Release Notes:
    - Sales: modules/sales.md
- About:
    - System Changes: about/release-notes.md
    - Contact Us: about/contact.md

markdown_extensions:
    - toc:
        permalink: true