==========
Pengenalan
==========

Model adalah representasi sebuah *Data Object*. Data Object dapat dianalogikan
sebagai sebuah *Table* dalam *Relational Database*. Model mempunyai beberapa
komponen penting, yaitu ``attributes``, ``fields``, ``data``, ``views``,
``service``, dan ``ACL``.

Attributes
----------

Attributes adalah kelompok informasi dasar dari Model. Informasi dasar yang
dimaksud adalah seperti ``id``, ``name``, ``persistent``, dan ``version``.
Komponen Attributes, diawali dengan tag ``<attributes>`` dan mempunyai anak-anak
dengan tag ``<attribute>``. Pada tag ``<attribute>``, harus disertai dengan
sebuah attribute ``name``, di mana value dari attribute tersebut adalah sebagai
berikut,

- ``id``
    Mempunyai informasi tentang **identitas** dari model. Penamaan identitas model
    harus disertai ``id`` dari **Module** yang diletakkan pada awal (prefix) dan
    digabung dengan menggunakan *dot* (.).

- ``name``
    Informasi tentang **nama** sebuah Model.

- ``persistent``
    Bernilai ``True`` atau ``False``, yang menentukan apakah Model akan disimpan
    pada database atau tidak.

- ``version``
    Informasi tentang versi dari Model.

Fields
------

Fields dapat diartikan sebagai daftar kolom yang ada pada *Table* dalam
*Relational Database*. Namun tidak semua ``field`` akan dijadikan kolom, tetapi
hanya yang ditentukan  sajalah yang dijadikan sebuah kolom.

Fields dibedakan menjadi tiga kelompok, yaitu:

- **Common**
    Field umum seperti input box, calendar, dan lain-lain
- **Relational**
    Field yang mempunyai relasi ke Model lain, seperti *Foreign Key* pada SQL.
- **Functional**
    Field yang nilainya berasal dari sebuah ``function`` dari server atau pun
    dari client. Function akan mengembalikan nilai yang ditampilkan sesuai
    format nilai Field yang dituju.

Selengkapnya dapat dilihat pada dokumentasi Fields_.

.. _Fields: https://github.com/pararaton/efitrac/wiki/Fields

